version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./SharePilot:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 526996
      MYSQL_DATABASE: sharepilot      
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./SharePilot/install/db.sql:/docker-entrypoint-initdb.d/db.sql

volumes:
  mysql_data:
