version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
      - "443:443"
      - "9003:9003"  # Xdebug port
    volumes:
      - ./mycert.crt:/etc/ssl/certs/mycert.crt
      - ./mycert.key:/etc/ssl/private/mycert.key
      - ./SharePilot:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: 526996
      MYSQL_DATABASE: sharepilot      
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./SharePilot/install/db_docker.sql:/docker-entrypoint-initdb.d/db_docker.sql

volumes:
  mysql_data:
